version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: minha_senha_root
      MYSQL_DATABASE: meu_banco
      MYSQL_USER: meu_usuario
      MYSQL_PASSWORD: minha_senha_usuario
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mysql_data:
