spring.jpa.open-in-view=true

spring.datasource.url=jdbc:mysql://localhost:3306/meu_banco
spring.datasource.username=meu_usuario
spring.datasource.password=minha_senha_usuario

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
